[project]
name = "med"
version = "0.1.0"
description = "This package is for the project using a multimodal LLM to interprete medical reports and images"
authors = [
    {name = "Jeanette"}
]
license = {text = "To be determined"}
readme = "README.md"
requires-python = ">3.12"
dependencies = [
    "openai (>=1.83.0,<2.0.0)",
    "litellm (>=1.72.0,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
