---
version: 1
disable_existing_loggers: False
formatters:
  json:
    format: "%(asctime)s %(process)d %(name)s %(levelname)s %(message)s"
    class: src.utils.logging.UnicodeJsonFormatter
    # class: pythonjsonlogger.jsonlogger.JsonFormatter
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
    charset: utf8
  pretty_json:
    class: src.utils.logging.PrettyJSONFormatter
    format: "%(asctime)s %(process)d %(name)s %(levelname)s %(message)s %(json_data)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
    charset: utf8

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: json

  debug_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: json
      filename: debug.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
      delay: True

  info_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: json
      filename: info.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
      delay: True

  error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: json
      filename: errors.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8
      delay: True

root:
  level: INFO
  handlers: [console, debug_file_handler, info_file_handler, error_file_handler]